
' This file is used by Code Analysis to maintain SuppressMessage 
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given 
' a specific target and scoped to a namespace, type, member, etc.

<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'String.CompareTo(String)' could vary based on the current user's locale settings. Replace this call in 'ActuarialStuff.CategoryListBox.CountedCategoryItem.CompareTo(ActuarialStuff.CategoryListBox.CountedCategoryItem)' with a call to 'String.Compare(String, String, System.StringComparison)'.", Justification:="<Pending>", Scope:="member", Target:="~M:ActuarialStuff.CategoryListBox.CountedCategoryItem.CompareTo(ActuarialStuff.CategoryListBox.CountedCategoryItem)~System.Int32")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Function MyWindows.Create__Instance__(Of T)(Instance As T) As T' passes a literal string as parameter 'message' of a call to 'Sub InvalidOperationException.New(message As String)'. Retrieve the following string(s) from a resource table instead: ""The window cannot be accessed via My.Windows from the Window constructor."".", Justification:="<Pending>", Scope:="member", Target:="~M:ActuarialStuff.My.MyWpfExtension.MyWindows.Create__Instance__``1(``0)~``0")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Sub SoaTableFilter.ReloadTableList()' passes a literal string as parameter 'value' of a call to 'Property Set TextBlock.Text(value As String)'. Retrieve the following string(s) from a resource table instead: ""Filtered SOA Tables   #0"".", Justification:="<Pending>", Scope:="member", Target:="~M:ActuarialStuff.SoaTableFilter.ReloadTableList")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Sub SoaTableSelectorComparer.ReloadTableList()' passes a literal string as parameter 'value' of a call to 'Property Set TextBlock.Text(value As String)'. Retrieve the following string(s) from a resource table instead: ""SOA Tables   #0"".", Justification:="<Pending>", Scope:="member", Target:="~M:ActuarialStuff.SoaTableSelectorComparer.ReloadTableList")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Sub SoaTableSelectorViewer.ReloadTableList()' passes a literal string as parameter 'value' of a call to 'Property Set TextBlock.Text(value As String)'. Retrieve the following string(s) from a resource table instead: ""SOA Tables   #0"".", Justification:="<Pending>", Scope:="member", Target:="~M:ActuarialStuff.SoaTableSelectorViewer.ReloadTableList")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'Sub TableLoadDialog.BtnLoadSelected_Click(sender As Object, e As RoutedEventArgs)' passes a literal string as parameter 'value' of a call to 'Property Set FileDialog.Filter(value As String)'. Retrieve the following string(s) from a resource table instead: ""SOA Tables (t*.xml)|t*.xml"".", Justification:="<Pending>", Scope:="member", Target:="~M:ActuarialStuff.TableLoadDialog.BtnLoadSelected_Click(System.Object,System.Windows.RoutedEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1812:Application is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification:="<Pending>", Scope:="type", Target:="~T:ActuarialStuff.Application")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2224:Override Equals on overloading operator equals", Justification:="<Pending>", Scope:="type", Target:="~T:ActuarialStuff.CategoryListBox.CountedCategoryItem")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1067:Type ActuarialStuff.CategoryListBox.CountedCategoryItem should override Equals because it implements IEquatable<T>", Justification:="<Pending>", Scope:="type", Target:="~T:ActuarialStuff.CategoryListBox.CountedCategoryItem")>